const books = [
  {
    id: 31,
    color: "white",
    authors: "Jordan Peterson",
    title: "12 Rules for Life: An Antidote to Chaos",
    slug: "12-rules-for-life:-an-antidote-to-chaos",
    available: true,
    borrowedBy: [3],
  },
  {
    id: 9,
    color: "yellow",
    authors: "George R.R. Martin",
    title: "A Clash of Kings",
    slug: "A-clash-of-kings",
    available: true,
    borrowedBy: [],
  },
  {
    id: 12,
    color: "white",
    authors: "George R.R. Martin",
    title: "A Dance With Dragons",
    slug: "a-dance-with-dragons",
    available: true,
    borrowedBy: [1, 3, 5],
  },
  {
    id: 11,
    color: "red",
    authors: "George R.R. Martin",
    title: "A Feast for Crows",
    slug: "a-feast-for-crows",
    available: true,
    borrowedBy: [2, 5],
  },
  {
    id: 8,
    color: "blue",
    authors: "George R.R. Martin",
    title: "A Game of Thrones",
    slug: "a-game-of-thrones",
    available: true,
    borrowedBy: [4, 1],
  },
  {
    id: 10,
    color: "green",
    authors: "George R.R. Martin",
    title: "A Storm of Swords",
    slug: "a-storm-of-swords",
    available: true,
    borrowedBy: [],
  },
  {
    id: 25,
    color: "black",
    authors: "Leigh Bardugo",
    title: "Six of Crows",
    title: "six-of-crows",
    available: true,
    borrowedBy: [4, 3, 2, 1, 5],
  },
  {
    id: 30,
    color: "yellow",
    authors: "Agatha Christie",
    title: "Curtain: Poirot's Last Case",
    slug: "curtain:-poirot's-last-case",
    available: true,
    borrowedBy: [3],
  },
];

export default books;
