const books = [
  {
    id: 1,
    author: "Jordan Peterson",
    title: "12 Rules for Life: An Antidote to Chaos",
    slug: "12-rules-for-life:-an-antidote-to-chaos",
    genre: ["Self-Help"],
    available: true,
    borrowedBy: [3],
  },
  {
    id: 2,
    author: "Blake Crouch",
    title: "Dark Matter",
    slug: "dark-matter",
    genre: ["Sci-Fi", "Thriller"],
    available: true,
    borrowedBy: [],
  },
  {
    id: 3,
    author: "Robin Sloan",
    title: "Mr. Penumbra's 24-Hour Bookstore",
    slug: "mr.-penumbra's-24-hour-bookstore",
    genre: ["Suspense", "Fantasy"],
    available: true,
    borrowedBy: [1, 3, 5],
  },
  {
    id: 4,
    author: "George R.R. Martin",
    title: "A Feast for Crows",
    slug: "a-feast-for-crows",
    genre: ["Fantasy"],
    available: true,
    borrowedBy: [2, 5],
  },
  {
    id: 5,
    author: "Eric Ries",
    title: "The Lean Startup",
    slug: "the-lean-startup",
    genre: ["Business", "Entrepreneurship"],
    available: true,
    borrowedBy: [4, 1],
  },
  {
    id: 6,
    author: "George R.R. Martin",
    title: "A Storm of Swords",
    slug: "a-storm-of-swords",
    genre: ["Fantasy"],
    available: true,
    borrowedBy: [],
  },
  {
    id: 7,
    author: "Leigh Bardugo",
    title: "Six of Crows",
    slug: "six-of-crows",
    genre: ["Fantasy"],
    available: true,
    borrowedBy: [4, 3, 2, 1, 5],
  },
  {
    id: 8,
    author: "Agatha Christie",
    title: "Curtain: Poirot's Last Case",
    slug: "curtain:-poirot's-last-case",
    genre: ["Crime", "Mystery"],
    available: true,
    borrowedBy: [3],
  },
];

export default books;
